GET http://localhost:3000/usuarios
###
DELETE http://localhost:3000/usuarios/220
###
POST http://localhost:3000/usuarios
Content-Type: application/json

{
    "nombre": "Pedro",
    "apellido": "Pascal",
    "telefono": "3425138732",
    "direccion": "Pedro Vittori 3691",
    "detalle_usuario": "Ninguno",
    "zona": "Centro"
}
###
GET  http://localhost:3000/viandas
###
POST http://localhost:3000/viandas
Content-Type: application/json

{
    "nombre": "Keto",
    "precio": 2900
}
###
DELETE http://localhost:3000/viandas/2
###
GET http://localhost:3000/pedidos
###
GET http://localhost:3000/pedidos/3
###
POST http://localhost:3000/pedidos/
Content-Type: application/json

{
"id_users": 220,
"detalle_pedido": "probando cascade delete user/pedido",
"forma_pago": "eliminar el usuario deberia eliminar el pedido",
"dia": "Lunes",
"semana": false
}
###
PATCH http://localhost:3000/pedidos/79
Content-Type: application/json

{
    "estado": "entregado"
}
###
DELETE http://localhost:3000/pedidos/80
###
GET http://localhost:3000/items_pedido
###
POST http://localhost:3000/items_pedido
Content-Type: application/json

{
    "id_vianda": 5,
    "id_pedido": 81,
    "detalle_pedido": "",
    "cantidad": 2
}